//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMVCUI.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorun
    {
        public int Id { get; set; }
        public string TITLE { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> DEADLINE { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Status Status { get; set; }
    }
}
